### ISSUE TITLE
TypeError: makedirs() got an unexpected keyword argument 'exist_ok'

### ISSUE THREAD

**Issue by l29ah** [hauzer/scrobbler#1]
‰ scrobbler add-user
Traceback (most recent call last):
  File "/usr/lib/python-exec/python2.7/scrobbler", line 11, in <module>
    load_entry_point('scrobblerh==1.1.2.post1', 'console_scripts', 'scrobbler')()
  File "/usr/lib64/python2.7/site-packages/scrobbler/scrobbler.py", line 269, in main
    os.makedirs(dirs.user_data_dir, exist_ok = True)
TypeError: makedirs() got an unexpected keyword argument 'exist_ok'

**Comment by hauzer** [comment]
The error is due to the differences between Python 2 and 3 versions of `os.makedirs()`. `scrobbler` doesn't currently support Python 2 nor is it planned. Use Python 3.
