### ISSUE TITLE
add-user fails to show an URL

### ISSUE THREAD

**Issue by l29ah** [hauzer/scrobbler#2]
‰ scrobbler add-user
The Last.fm authentication page will be opened, or its URL printed here.
Press enter to continue.

[nothing happens]

Press enter after granting access.
Unauthorized Token - This token has not been authorized

**Comment by hauzer** [comment]
Care to provide some information about your system? OS/distro, DE/WM and browser primarily.

**Comment by l29ah** [comment]
On Thu, Oct 06, 2016 at 09:39:02AM -0700, Никола Вукосављевић wrote:
> Care to provide some information about your system? OS/distro, DE/WM and browser primarily.

Gentoo linux, xmonad, firefox in firejail. Calling `$BROWSER <url>` works.

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Comment by hauzer** [comment]
Must be Python's webbrowser module not handling something in your setup. I'll add a workaround option which disables invoking the browser and instead forces the URL to be printed.

**Comment by hauzer** [comment]
Added `-x/--dont-invoke-browser` option to `add-user` which forces the URL to printed out. New version on PyPI.
