### ISSUE TITLE
Track not scrobbled if it contains a dot

### ISSUE THREAD

**Issue by lead0r** [hauzer/scrobbler#3]
If a track contains a dot in the track name, I get an "Error: ." while trying to scrobble it.
Is it possible to resolve this issue?

**Comment by hauzer** [comment]
I'll look into it.

**Comment by hauzer** [comment]
I've tested `a.a`, `a.`, `.a`, and they all work fine. Can you provide more information? Your OS and the exact name of the song would help.

**Comment by lead0r** [comment]
They work for me as well. I'm on macOS Sierra 10.12.1.

The name of the song is "scntfc_exfiltrat0n_3_b_deleted.wav". Yes, with the .wav. Is it possible that that's the problem? I tried "scntfc_exfiltrat0n_3_b_deletedw.av" and it worked fine.

**Comment by hauzer** [comment]
Looks like it's a limitation of the Last.fm API. Scrobbling `.rar`, `.exe`, `.jpg`, or similar non-audio related extensions works, but `.wav`, `.ogg`, `.mp3`, and similar, don't. Try it on other scrobblers, like [this](http://universalscrobbler.com) one, or [this](http://scrobbler.jankuca.com/) one. They both say that the offending tracks are successfully scrobbled, but if you look on your profile, they're nowhere to be found. Can you confirm?

**Comment by lead0r** [comment]
Yes, I can confirm that. Well, I'll have to change the track name a little bit, as I also understand why Last.fm is using this limitation. Or do you have another idea?

**Comment by hauzer** [comment]
The Last.fm API is broken in so many ways. I wouldn't recommend changing your library to accommodate all of its quirks. I'd leave the track's name be as it is, and simply not care about it not being scrobbled. If you really want it scrobbled, there's no other way except changing its name. There's simply nothing we can do on our side until Last.fm changes things on theirs.

**Comment by lead0r** [comment]
Okay, thank you. I found this list of forbidden names (although the list is very old): http://www.last.fm/forum/21713/_/70366/1#f714635

**Comment by hauzer** [comment]
Well, maybe this issue will help someone in the future. Thanks for the effort.
