### ISSUE TITLE
Line 46 Error

### ISSUE THREAD

**Issue by aeseok** [hauzer/scrobbler#5]
C:\Users\A**** *\Downloads\scrobbler-master\scrobbler>scrobbler.py add user
File "C:\Users\A *****\Downloads\scrobbler-master\scrobbler\scrobbler.py", line 46
from . import
^
SyntaxError: invalid syntax

Please forgive me if I'm doing something wrong this is my first time working with .py files.

**Comment by hauzer** [comment]
Duplicate of #6

**Comment by hauzer** [comment]
I'm not sure what you're trying to do here. If you want to use the program normally, just install it via pip. On Windows for example: `py -3 -m pip install scrobblerh`.
